[package]
name = "ycal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde", "unstable-locales"] }
clap = { version = "4", features = ["derive"] }
ramhorns = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
